"""add status to chat messages

Revision ID: 001338860e72
Revises: c9dcc088ee5f
Create Date: 2026-05-13 12:31:35.145461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001338860e72'
down_revision: Union[str, Sequence[str], None] = 'c9dcc088ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('chat_messages', 'status')
    # ### end Alembic commands ###
