"""add created_at to ticket replies

Revision ID: f1fbdb011236
Revises: 001338860e72
Create Date: 2026-05-17 17:37:27.829000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fbdb011236'
down_revision: Union[str, Sequence[str], None] = '001338860e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_replies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_replies', 'created_at')
    # ### end Alembic commands ###
